"""Regenerate every table and figure from ``outputs/``.

Usage::

    python -m hyperbolic_world_model.reporting.make_report --outputs outputs --report outputs/report
    bash scripts/make_report.sh            # the same, through uv

The report is a pure function of ``outputs/**/metrics.json`` and ``outputs/**/*_curves.csv``:
previously generated files are removed first, every group is iterated in sorted order and PNG
metadata is stripped, so running it twice on the same ``outputs/`` gives byte-identical results.
Nothing in ``outputs/report/`` is hand-edited.

What is written (see ``outputs/README.md``):

``tables/results.md``
    every ``(run, task, metric)`` with its geometry, curvature, latent dimension and seed;
``tables/summary.md``
    mean ± std over seeds per configuration;
``tables/<task>__<metric>__curvature_sweep.md``
    for every result metric with more than one curvature: the ``(geometry, K) x dim`` grid;
``tables/best_curvature_vs_euclidean.md``
    per task, metric and dimension: the Euclidean baseline against the best swept curvature and
    whether the difference exceeds one seed std at both configurations;
``tables/dimension_efficiency.md``
    log2 AUC of every metric-vs-dimension curve and the dimension at which each geometry reaches
    the Euclidean baseline;
``figures/<task>__<metric>__vs_curvature.png`` and ``figures/<task>__<metric>__vs_dimension.png``
    one per result metric with more than one curvature / more than one dimension;
``figures/<task>__curves.png``
    every ``<task>_curves.csv`` overlaid (seeds averaged), one panel per curve column;
``README.md``
    an index of everything above.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from hyperbolic_world_model.reporting.curvature_sweep_plots import (
    CURVE_KEYS,
    plot_curvature_sweep,
    plot_dimension_curves,
    plot_task_curves,
)
from hyperbolic_world_model.reporting.tables import (
    best_curvature_table,
    collect_runs,
    dimension_efficiency_table,
    is_result_metric,
    results_table,
    summary_table,
    sweep_table,
    to_markdown,
)

HEADER = "_Generated by `scripts/make_report.sh`; all distances in each model's native geometry._"


def clean_report_dir(report: Path) -> None:
    """Remove files a previous run generated (tables, figures, index) but nothing else."""
    for pattern in ("tables/*.md", "figures/*.png", "README.md"):
        for path in sorted(report.glob(pattern)):
            path.unlink()


def collect_curves(runs: list[dict]) -> dict[str, pd.DataFrame]:
    """``task -> DataFrame`` of every ``<task>_curves.csv`` with the run keys and seed attached."""
    frames: dict[str, list[pd.DataFrame]] = {}
    for run in runs:
        for csv in sorted(Path(run["_path"]).glob("*_curves.csv")):
            task = csv.name[: -len("_curves.csv")]
            df = pd.read_csv(csv)
            for key in [*CURVE_KEYS, "seed"]:
                df[key] = run.get(key)
            frames.setdefault(task, []).append(df)
    return {task: pd.concat(dfs, ignore_index=True) for task, dfs in sorted(frames.items())}


def curve_x_column(df: pd.DataFrame) -> str | None:
    """The x axis of a curves table: ``horizon`` if present, else ``depth``."""
    for candidate in ("horizon", "depth"):
        if candidate in df.columns:
            return candidate
    return None


def _write_md(path: Path, title: str, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"# {title}\n\n{HEADER}\n\n{body}\n")
    return path


def make_report(outputs: Path, report: Path) -> list[Path]:
    """Regenerate ``report`` from ``outputs``; returns every file written, sorted."""
    outputs, report = Path(outputs), Path(report)
    clean_report_dir(report)
    runs = collect_runs(outputs)
    table = results_table(runs)
    summary = summary_table(table)
    tables_dir, figs_dir = report / "tables", report / "figures"
    written: list[Path] = []

    written.append(_write_md(tables_dir / "results.md", "Results (every run)", to_markdown(table)))
    written.append(
        _write_md(
            tables_dir / "summary.md", "Summary (mean ± std over seeds)", to_markdown(summary)
        )
    )

    best_rows, eff_rows = [], []
    if not summary.empty:
        for (task, metric), grp in summary.groupby(["task", "metric"], sort=True):
            if not is_result_metric(metric):
                continue
            stem = f"{task}__{metric}"
            n_curv = grp[grp["geometry"] != "euclidean"]["curvature"].nunique()
            n_dims = grp["latent_dim"].nunique()
            if n_curv > 1:
                written.append(
                    _write_md(
                        tables_dir / f"{stem}__curvature_sweep.md",
                        f"{task}: {metric} vs curvature",
                        to_markdown(sweep_table(summary, task, metric)),
                    )
                )
                written.append(
                    plot_curvature_sweep(grp, metric, figs_dir / f"{stem}__vs_curvature.png")
                )
            if n_dims > 1:
                written.append(
                    plot_dimension_curves(grp, metric, figs_dir / f"{stem}__vs_dimension.png")
                )
                eff_rows.append(dimension_efficiency_table(summary, task, metric))
            best_rows.append(best_curvature_table(summary, task, metric))
    best = (
        pd.concat(best_rows, ignore_index=True)
        if best_rows
        else best_curvature_table(summary, "", "")
    )
    written.append(
        _write_md(
            tables_dir / "best_curvature_vs_euclidean.md",
            "Best swept curvature vs the Euclidean baseline",
            to_markdown(best),
        )
    )
    eff = (
        pd.concat(eff_rows, ignore_index=True)
        if eff_rows
        else dimension_efficiency_table(summary, "", "")
    )
    written.append(
        _write_md(
            tables_dir / "dimension_efficiency.md",
            "Dimension efficiency (log2 AUC; dimension to reach the Euclidean baseline)",
            to_markdown(eff),
        )
    )

    for task, curves in collect_curves(runs).items():
        x = curve_x_column(curves)
        if x is None:
            continue
        written.append(plot_task_curves(curves, x, task, figs_dir / f"{task}__curves.png"))

    written = sorted(set(written))
    index = ["# Report", "", HEADER, "", f"Runs found: {len(runs)}", "", "## Tables", ""]
    index += [
        f"- [{p.name}]({p.relative_to(report).as_posix()})" for p in written if p.suffix == ".md"
    ]
    index += ["", "## Figures", ""]
    index += [
        f"- [{p.name}]({p.relative_to(report).as_posix()})" for p in written if p.suffix == ".png"
    ]
    readme = report / "README.md"
    readme.write_text("\n".join(index) + "\n")
    written.append(readme)
    return written


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description="Regenerate every table and figure from outputs/.")
    p.add_argument("--outputs", type=Path, default=Path("outputs"))
    p.add_argument("--report", type=Path, default=Path("outputs/report"))
    args = p.parse_args(argv)
    for path in make_report(args.outputs, args.report):
        print(path)


if __name__ == "__main__":
    main()
